# Generated by Django 5.1.3 on 2024-11-12 05:13

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=None, max_length=100, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(blank=None, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.CharField(choices=[('BARISTA', 'Barista'), ('CASHIER', 'Cajero'), ('MANAGER', 'Gerente'), ('CHEF', 'Chef'), ('SERVER', 'Mesero'), ('SUPERVISOR', 'Supervisor')], max_length=20)),
                ('hire_date', models.DateField()),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
