# Generated by Django 5.1.3 on 2024-11-12 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_is_staff_employee_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(null=True),
        ),
    ]
