# Generated by Django 5.1.3 on 2024-11-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_employee_hire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(blank=True, choices=[('BARISTA', 'Barista'), ('CASHIER', 'Cajero'), ('MANAGER', 'Gerente'), ('CHEF', 'Chef'), ('SERVER', 'Mesero'), ('SUPERVISOR', 'Supervisor')], max_length=20),
        ),
    ]
