# Generated by Django 5.1.3 on 2024-11-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('employee', '0009_employee_date_joined_employee_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='employee_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(blank=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='employee_user_set', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.CharField(blank=None, max_length=100, unique=True),
        ),
    ]
