# Generated by Django 5.1.3 on 2024-11-13 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('MOBILE_PAYMENT', 'Mobile Payment'), ('BANK_TRANSFER', 'Bank Transfer'), ('ONLINE_PAYMENT', 'Online Payment'), ('GIFT_CARD', 'Gift Card')], max_length=20)),
                ('payment_date', models.DateField()),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
    ]
